version: '2'
services:
  base:
    build: .
  hazel:
    extends: base
    ports:
      - "8080:8080"
    expose: 
      - "8080"
    volumes:
      - /var/data:/var/data
    entrypoint: 
      - webapp
  timer:
    extends: base
    volumes:
      - /var/data:/var/data
    entrypoint: 
      - timer
