apiVersion: v1
kind: Service
metadata:
  name: {{ include "remindbot.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "remindbot.name" . }}
    helm.sh/chart: {{ include "remindbot.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "remindbot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
